// Generated by CoffeeScript 1.6.2
(function() {
  var delay, getSeconds, timestamp;

  timestamp = function() {
    return +(new Date) * 0.001 | 0;
  };

  getSeconds = function(timeStr) {
    var time, unit, units, _, _ref;

    if (timeStr == null) {
      return 0;
    }
    units = {
      secs: 1,
      sec: 1,
      s: 1,
      mins: 60,
      min: 60,
      m: 60,
      hours: 3600,
      hour: 3600,
      h: 3600,
      days: 86400,
      day: 86400,
      d: 86400
    };
    _ref = timeStr.match(/([0-9.]+)([a-z]+)/i), _ = _ref[0], time = _ref[1], unit = _ref[2];
    if (unit in units) {
      return units[unit] * parseFloat(time);
    } else {
      return 0;
    }
  };

  delay = function(time, call) {
    var runner;

    if (typeof time === 'string') {
      time = 1000 * getSeconds(time);
    }
    runner = function() {
      return call((function() {
        return setTimeout(runner, time);
      }));
    };
    return setTimeout(runner, time);
  };

  exports.timestamp = timestamp;

  exports.getSeconds = getSeconds;

  exports.delay = delay;

}).call(this);
